theme: jekyll-theme-minimal
title: The title of your site
description: A short description of your site's purpose
logo:  a1ex-13.github.io/m4.jpg 
show_downloads: "true" or "false" to indicate whether to provide a download URL
google_analytics: Your Google Analytics tracking ID
